[package]
name = "chase-ai"
version = "0.1.0"
edition = "2021"
authors = ["Mitriyweb <mitriyweb@gmail.com>"]
description = "Controlled Local AI Execution Platform"

[lib]
name = "app"
path = "src/rs/app.rs"

[[test]]
name = "app"
path = "src/test/rs/app.rs"

[[test]]
name = "network_integration"
path = "src/test/rs/network_integration.rs"

[[bin]]
name = "chase-ai"
path = "src/rs/main.rs"

[dependencies]
anyhow = "1.0.86"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
if-addrs = "0.7.0"
toml = "0.8.14"
image = "0.25.1"
tray-icon = "0.14.3"
tao = "0.28.1"

[dev-dependencies]
tokio = { version = "1.38.0", features = ["full"] }
tempfile = "3.10.1"
